### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by enh-google** [ARM-software/optimized-routines#20]
ignoring all the spam from
```
math/math_config.h: In function ‘force_eval_float’:
math/math_config.h:188:18: warning: unused variable ‘y’ [-Wunused-variable]
   volatile float y = x;
                  ^
math/math_config.h: In function ‘force_eval_double’:
math/math_config.h:193:19: warning: unused variable ‘y’ [-Wunused-variable]
   volatile double y = x;
                   ^
```

it seems like the build is currently broken?

```
/usr/bin/ld: build/lib/libmathlib.a(s_powf.o): in function `__s_powf':
/tmp/optimized-routines/math/v_powf.c:208: undefined reference to `roundtoint'
/usr/bin/ld: /tmp/optimized-routines/math/v_powf.c:209: undefined reference to `converttoint'
```

here's the warnings that get lost in the spam:
```
math/v_powf.c: In function ‘__s_powf’:
math/v_powf.c:208:12: warning: implicit declaration of function ‘roundtoint’; did you mean ‘roundl’? [-Wimplicit-function-declaration]
       kd = roundtoint (ylogx); /* k */
            ^~~~~~~~~~
            roundl
math/v_powf.c:209:12: warning: implicit declaration of function ‘converttoint’ [-Wimplicit-function-declaration]
       ki = converttoint (ylogx);
            ^~~~~~~~~~~~
```

**Comment by nsz-arm** [comment]
please include the target you build for in the bug report. i assume it's aarch32 and yes i should probably disable __s_powf there.

unfortunately simd code cannot really be portable, and it currently only works with advsimd.

i recommend using -Werror=implicit-function-declaration since that's always an error, i have it in config.mk, i just didn't test this code on other targets than aarch64 (which is why i added a tag before i pushed the vector code)

**Comment by xboxfanj** [comment]
I can reproduce the issue in Android with aarch32.

**Comment by nsz-arm** [comment]
fixed at https://github.com/ARM-software/optimized-routines/commit/3d7ecfe37c0c05462f454940f515eb3ce726c5bc

**Comment by nsz-arm** [comment]
v_*.c actually has #if V_SUPPORTED which is only set on aarch64, s_*.c is scalar code and originally i assumed it will just work portably, but now i see there can be various problems.

if you use your own makefile then v_*, s_* and vn_* should be excluded if you don't care about simd math functions. (however the test and benchmark code has references to the s_* functions for now.. i will fix that, but i'm not yet sure what's the best way to factor that)

and yes i plan to do tagged releases as there are various projects that want to use this repo as upstream, but i also want to be able to publish half cooked code for particular use-cases (e.g. aarch64 simd math code), i might add a note about it to the README later.

**Comment by enh-google** [comment]
> v__.c actually has #if V_SUPPORTED which is only set on aarch64, s__.c is scalar code and originally i assumed it will just work portably, but now i see there can be various problems.
> 
> if you use your own makefile then v__, s__ and vn_* should be excluded if you don't care about simd math functions.

i assume some other part of ARM will be hassling me about them at some point; they're starting to make noises about SVE string routines :-)

but, no, i don't care right now. and even when i do care, i expect it'll only be for arm64. (x86-64 seems likely to go with basically "blobs" --- the compiler output from icc compiling unknown source, afaict.)

> (however the test and benchmark code has references to the s_* functions for now.. i will fix that, but i'm not yet sure what's the best way to factor that)

the main reason i'm looking at this code right now is because i'm trying to work out how to get these math tests (which seem like the best ones i've seen --- too many are no more sophisticated than just random data) into Android's Compatibility Test Suite (CTS). from my perspective, a way to "just test what's exposed in libm" is the switch i need. i specifically don't want to force any SoC vendor to use this _implementation_, but i do want to ensure that every SoC vendor's code behaves the same. which means i can only test libm API.

(right now we've only ever run these tests manually on a single device when taking an update from upstream. my first step is to get the tests running in presubmit so they're at least run on a variety of devices automatically if any change is made to this code or the old "msun" libm code. then i'll worry about CTS. but that's the plan anyway.)

> and yes i plan to do tagged releases as there are various projects that want to use this repo as upstream, but i also want to be able to publish half cooked code for particular use-cases (e.g. aarch64 simd math code), i might add a note about it to the README later.

excellent. that's ideal for us.
