### ISSUE TITLE
better documentation of WANT_ROUNDING?

### ISSUE THREAD

**Issue by enh-google** [ARM-software/optimized-routines#23]
thanks for the clarification of `WANT_ERRNO` in https://github.com/ARM-software/optimized-routines/issues/16#issuecomment-572009659. (i'm trying to get the CLA sorted so i can send you patches, and assuming i do i'll send a patch to elaborate on that in `math_config.h`.)

could you explain `WANT_ROUNDING` in more detail? it's currently set to 0 for Android, but i don't know whether that's the right setting (given that the _default_ behavior is to use 1 if nothing is set).

thanks!

**Comment by Wilco1** [comment]
WANT_ROUNDING means you get correct results for special cases when you call math functions using different rounding modes. Eg. don't return -0.0 due to rounding to -infinity. This isn't needed if there is no fenv support and you use round-to-nearest as the rounding mode.

**Comment by enh-google** [comment]
so that sounds like this is a bug in Android at the moment then, since we do have fenv. i'll test again with WANT_ROUNDING and switch Android over...

**Comment by Wilco1** [comment]
I wouldn't say it's a bug since nobody outside of HPC ever changes rounding modes. Also compilers aren't great at supporting different rounding modes - even if available, fenv support is still very basic.

**Comment by enh-google** [comment]
i've removed the -D of WANT_ROUNDING in Android so we just take the default now. thanks for the clarification!

**Comment by Wilco1** [comment]
I have updated the comments around WANT_ERRNO and WANT_ROUNDING (also WANT_ERRNO is now 0 by default).
