### ISSUE TITLE
Support building/testing stpcpy

### ISSUE THREAD

**Issue by pcc** [ARM-software/optimized-routines#24]
In http://r.android.com/1243146 @enh-google noted that the stpcpy implementation in this repository is not currently being built or tested in the optimized-routines repository (it does appear to be built/tested as part of glibc though).

It would be good to support building and testing the stpcpy in this repository given that we're starting to use it on Android.

**Comment by enh-google** [comment]
(and if you check in a stpcpy.S that's basically #define followed by #include, that makes our build simpler :-) )

**Comment by Wilco1** [comment]
You're right, stpcpy was supported but not tested. I've now added a test and a basic stpcpy.S file.

**Comment by nsz-arm** [comment]
fixed in https://github.com/ARM-software/optimized-routines/commit/9be4a9b833dbdb708f7b9bbd20511ea4b528ccac

**Comment by enh-google** [comment]
that looks ideal. thanks!
