### ISSUE TITLE
SCTLR_EL2.A alignment check breaks memset

### ISSUE THREAD

**Issue by jkrh** [ARM-software/optimized-routines#41]
I tried to take these functions to use in our KVM fork (https://github.com/jkrh/kvms) but looks like not all of the code is written such that SCTLR.A alignment checks can be on.

[!!!!!!!!!!!!] Unhandled exception in EL2 at 0x0001000074d4 (memset.S:55)
[!!!!!!!!!!!!] VTTBR_EL2 (0x00000386d000) ESR_EL2 (0x000096000061) FAR_EL2 (0x00010000cfe8)

The first non-aligned memset after the mmu enable explodes to alignment fault if SCTRL.A is set. I suppose this is probably not intended?

**Comment by Wilco1** [comment]
I've used unaligned accesses extensively to improve performance. So if you want to use these string functions, you will need to disable alignment checks.

**Comment by jkrh** [comment]
Bummer, I'm somewhat uneasy about disabling the alignment checks. Does the Linux kernel also use this code without the strict alignment checks?

**Comment by Wilco1** [comment]
Linux enables unaligned accesses. Modern hardware supports efficient unaligned accesses, and string functions are a lot faster as a result, so you might as well take advantage.

**Comment by jkrh** [comment]
Indeed, SCTLR_EL1 seems to confirm. Madness, but ok. I'll give it a spin on the real hw to see if it the 'other EL2 entity' in question is happy about the move as well.

**Comment by jkrh** [comment]
Duh, the hw doesn't seem to like this even in the early boot when the MMU is still disabled, generating alignment errors. Need to hunt the bit causing this..

**Comment by Wilco1** [comment]
You cannot use unaligned accesses until after the MMU is enabled indeed.

**Comment by Wilco1** [comment]
It won't help much if caches are still disabled - you want to avoid accessing a lot of memory before the MMU and caches are set up properly. For boot code I would suggest writing a special memset (eg. a loop of STP xzr, xzr, [x0], 16 will work if you ensure everything is aligned).

**Comment by jkrh** [comment]
Yeah noticed. While it did memset the boot timestamp nicely, cleaning up the page tables exploded and that stuff is perfectly aligned.

**Comment by Wilco1** [comment]
Presumably that is due to trying to execute ``mrs	zva_val, dczid_el0``. It's simply not designed to be used outside of EL0.

**Comment by jkrh** [comment]
Wait, so you're saying it doesn't specifically utilize unaligned accesses and could still be fixed for the purpose?

**Comment by Wilco1** [comment]
It will only use unaligned accesses if the pointer or size are not a multiple of 16 bytes. It would be quicker and easier to write something that exactly suits your needs rather than try to hack this implementation.

**Comment by jkrh** [comment]
Sure, I'll add the asm loop to initialize the tables themselves and what ever is required before the mmu is up. Do you see an issue using this code after the mmu is up with unaligned accesses enabled in the EL2?

**Comment by jkrh** [comment]
So there's that now for the early init https://github.com/jkrh/kvms/commit/6d2bf146645f778ad6ddc65b3d3521db0bb5c711

Trying to see now if this would work better in EL2 after the above patch. Since we grab the ownership of copy_to/from_user from the kernel, all the performance ever possible is highly desired.

**Comment by jkrh** [comment]
Adapted to handcrafted asm loops / 16 byte aligned structs during the boot & switched to nonaligned accesses after the init. All works fine now, thanks.
