### ISSUE TITLE
question: mops?

### ISSUE THREAD

**Issue by SchrodingerZhu** [ARM-software/optimized-routines#45]
I see that `armv8.8-a` also introduces MOPS extension including stuffs like `CYPE`. MOPS is not utilized in the routines in this repo. 

I wonder what will this kind of extension be like in real-world CPUs. Will it be like `REP MOVSB` in x86 world (in the means that it will suffer a slow down at starting up but it may then become a suitable choice for medium to large size memory copy)?

**Comment by Wilco1** [comment]
It's not needed since compilers can already inline the instructions. GLIBC might get an ifunc supporting MOPS. There are no implementations yet, but there would be no point if it couldn't do all copies efficiently.
