### ISSUE TITLE
Build is broken due to unexpected token in argument list

### ISSUE THREAD

**Issue by google-mirror** [ARM-software/optimized-routines#46]
```
[armeabi-v7a] Compile thumb  : optimized-routines <= memcpy.S
[armeabi-v7a] Compile thumb  : optimized-routines <= memset.S
[armeabi-v7a] Compile thumb  : optimized-routines <= strlen-armv6t2.S
jni/optimized-routines/string/arm/strlen-armv6t2.S:49:13: error: unexpected token in argument list
 prologue 4 5 push_ip=HAVE_PAC_LEAF
            ^
jni/optimized-routines/string/arm/strlen-armv6t2.S:110:13: error: unexpected token in argument list
 epilogue 4 5 push_ip=HAVE_PAC_LEAF
```

prologue and epilogue not defined when defined (__ arm __)

**Comment by nsz-arm** [comment]
thanks for the report. fixed in https://github.com/ARM-software/optimized-routines/commit/8e0a666f7840c745fcb9fe9d977a95c3d13ae246

**Comment by nsz-arm** [comment]
> Does aarch64/strcmp-sve.S MTE compatible? Which should I choose if both HWCAP2_MTE and HWCAP_SVE are set?

it should be mte compatible. as with any other string function you may want to benchmark for a particular system and workload but in general i'd expect the sve variant to be the right choice on a system with sve.

**Comment by xboxfanj** [comment]
@Wilco1 does that include memcpy?  It sounded like that was a performance improvement based on your commit message and I saw it was also committed to glibc.

**Comment by Wilco1** [comment]
No that does not apply to memcpy which has been tuned and is faster than the Neon version. The other SVE functions were written years ago before CPUs with SVE were available, so there are likely tweaks that can make them significantly faster.

**Comment by enh-google** [comment]
> No that does not apply to memcpy which has been tuned and is faster than the Neon version. The other SVE functions were written years ago before CPUs with SVE were available, so there are likely tweaks that can make them significantly faster.

is anyone working on that? please tag me to pull updates into AOSP any time you have a significant improvement...

(and let me know if there's anyone at Arm we should be hassling to get you more time to work on stuff like that! :-) )
