### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by xboxfanj** [ARM-software/optimized-routines#47]
Hi, it has been a while since the most recent release, but there have been many improvements since then.  Are there plans for a new release?  The Wiki says TBD.  The Android Open Source Project merges release tags, so it is currently missing SVE memcpy and other improvements to the string routines.

**Comment by enh-google** [comment]
(yeah, i generally assume that projects that have tags take such things seriously, and we should stick to the tags.)

**Comment by nsz-arm** [comment]
we will roll a new release, but not this year. is a 2023 february release acceptable?

**Comment by enh-google** [comment]
february -- especially if you mean "end of" -- is a bit late in the year for 2023's Android release. so if there's anything that should be in that release (remembering that 2024 devices will initially ship with 2023's code), early january would be better.

(on the bright side, there are unlikely to be _subtle_ issues from this code, so if there's anything particularly worthwhile we could maybe squeeze it in.)

**Comment by Wilco1** [comment]
These improvements are planned to be added to the next GLIBC too (end of January release). We likely could tag a bit earlier, however GLIBC gives wider testing coverage so it is a good idea to take advantage of that.

**Comment by nsz-arm** [comment]
fyi, i plan to tag a release tomorrow.

**Comment by nsz-arm** [comment]
released v23.01 at https://github.com/ARM-software/optimized-routines/commit/56e3bf05c19c4e28e1f5edd9093c712f16c5c32a

**Comment by enh-google** [comment]
for the new "pl/...          - separately maintained performance library code." line in README.md, since that seems like the bulk of the changes, is there any more documentation on what that stuff is and who'd use it, and for what?

**Comment by nsz-arm** [comment]
it's a directory where we may dump code.

pl/math/ may not be benchmarked on as many cores as math/ code and may not have the same quality guarantees (it is developed by different ppl focusing on hpc. we may merge some of their work into math/ at some point). you are not supposed to worry about that code but you can experiment with it if you want.

**Comment by enh-google** [comment]
> you are not supposed to worry about that code

thanks, that's answers my real question. (would it be worth s/pl/pending/ or something to make this obvious?)

> we may merge some of their work into math/ at some point

meaning the code in math/ might lose some of its ulp accuracy at some point in future? (or is that not what you mean by "quality guarantees"?)

**Comment by nsz-arm** [comment]
> > we may merge some of their work into math/ at some point
> 
> meaning the code in math/ might lose some of its ulp accuracy at some point in future? (or is that not what you mean by "quality guarantees"?)

meaning that we might improve the quality and perf of some of the pl/math/ code such that it is reasonable for inclusion into math libraries.

**Comment by enh-google** [comment]
> meaning that we might improve the quality and perf of some of the pl/math/ code such that it is reasonable for inclusion into math libraries

"quality" means different things to different people though --- glibc (to an outsider) at least seems a lot happier to trade accuracy for performance than we've been on Android, say. but it sounds like -- from the "and" in "quality and perf" -- you're saying "we're only interested in changes that improve performance while also improving [or at least not reducing] accuracy"? or do you mean something else by "quality"?

**Comment by Wilco1** [comment]
Historically GLIBC accepted absolutely horrible performance for correctly rounded math functions (with slowdowns reported of over 100000 times for some inputs). I fixed those slowdowns by removing the correctly rounded functions (which didn't affect their ULP much). Also the AOR math functions were added to GLIBC resulting in major performance gains while giving good (often better) accuracy.

So I'm curious as to what you mean - in which cases does Android have better accuracy for example? My understanding is that Android uses the same ancient fdlibm code.

**Comment by enh-google** [comment]
> Historically GLIBC accepted absolutely horrible performance for correctly rounded math functions (with slowdowns reported of over 100000 times for some inputs). I fixed those slowdowns by removing the correctly rounded functions (which didn't affect their ULP much). Also the AOR math functions were added to GLIBC resulting in major performance gains while giving good (often better) accuracy.

ah, okay --- like i said, most of what we know about glibc is second hand at best. as long as the goal is similar ulp, that's fine by me.

> So I'm curious as to what you mean - in which cases does Android have better accuracy for example? My understanding is that Android uses the same ancient fdlibm code.

yes and no. ART literally uses ancient fdlibm (for StrictMath), and bionic is -- as usual -- a mix of things. it's mostly freebsd with a few netbsd complex trig functions that freebsd doesn't yet have, but with the AOR routines in many cases.

the accuracy concerns are mostly about code we've _rejected_ --- we haven't had much recently, but it used to be pretty common to get submissions that improved performance, often in return for horrendous damage to accuracy. (my [least] favorite example being the sin/cos/sincos "optimization" back in the days when Android had that "fake CRT TV" effect when you turned it off; instead of the raster collapsing to a line and then disappearing, the new routines [which looked great on the meaningless microbenchmarks you see mentioned in device reviews] cause the line to just bounce forever. ever since, i've been in fear of more subtle damage creeping in! see also `-ffast-math` and friends.)

but it sounds like we have similar goals here anyway, so i'll relax and look forward to that. (but i still think a bit more documentation and/or more intention-revealing directory name would be helpful!)

**Comment by enh-google** [comment]
(fwiw, the quality of your math tests and the clear distinction between different kinds of test -- as opposed to the typical "here's a bunch of stuff that looks machine generated and may or may not just be random inputs tied to whatever results our current implementation produces" i've seen elsewhere -- is what gave me the confidence to use any of these routines in the first place. so congratulations on the good work there!)
