### ISSUE TITLE
tanf routine is not accurate enough

### ISSUE THREAD

**Issue by xboxfanj** [ARM-software/optimized-routines#5]
The tanf routine is not accurate enough to pass the CTS Bionic Test Cases on Android 8.1
on MSM8998

05-20 17:36:55 I/ConsoleReporter: [750/1866 arm64-v8a CtsBionicTestCases RCLLHP1790300655] math#tanf_intel fail: bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-3.9561114311218262) != actual (-3.9561119079589844)
Failed on element 60
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (3.9561114311218262) != actual (3.9561119079589844)
Failed on element 61
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-0.21544662117958069) != actual (-0.2154465913772583)
Failed on element 104
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (0.21544662117958069) != actual (0.2154465913772583)
Failed on element 105
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (0.99999940395355225) != actual (0.9999992847442627)
Failed on element 218
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-0.99999940395355225) != actual (-0.9999992847442627)
Failed on element 219
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (1.622123122215271) != actual (1.6221233606338501)
Failed on element 463
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-1.622123122215271) != actual (-1.6221233606338501)
Failed on element 464
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (0.99999940395355225) != actual (0.9999992847442627)
Failed on element 831
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-0.99999940395355225) != actual (-0.9999992847442627)
Failed on element 832
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (0.99999988079071045) != actual (0.9999997615814209)
Failed on element 833
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-0.99999988079071045) != actual (-0.9999997615814209)
Failed on element 834
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (0.99999690055847168) != actual (0.99999678134918213)
Failed on element 873
bionic/tests/math_data_test.h:(173) Failure in test math.tanf_intel
expected (-0.99999690055847168) != actual (-0.99999678134918213)
Failed on element 874
math.tanf_intel exited with exitcode 1.

**Comment by nsz-arm** [comment]
tanf has < 4ulp error, if that's not good enough for a use-case then don't use it.
