### ISSUE TITLE
Reference optimized-routines in source code

### ISSUE THREAD

**Issue by Bloodymoom** [ARM-software/optimized-routines#50]
Hi
There is a simple question, please take the liberty of asking.
How do I write this code if I want to reference this optimized-routines in my own source code?

**Comment by nsz-arm** [comment]
you can link your binaries against the libraries of optimized-routines, but ultimately the goal is to contribute most of these functions to libc projects so application code can keep using the platform libc and benefit from the optimizations without doing anything special. we don't expect stand-alone optimized-routines to be widely deployed and linked against.

you may also copy code from optimized-routines to try/benchmark something, but this is not the intended long term use.
