### ISSUE TITLE
Fail to build on ARM

### ISSUE THREAD

**Issue by hs0210** [ARM-software/optimized-routines#54]
Recently, the upstream optimized-routines fails to build on ARM, pleases help check.

Steps:
```
# yum install -y gcc glibc-static mpfr-devel libmpc-devel
# cp config.mk.dist config.mk
# make
```

Build log:
[build.log](https://github.com/ARM-software/optimized-routines/files/11551834/build.log)

**Comment by Wilco1** [comment]
What does gcc -v say? It looks like you're using an old compiler - the vector code requires GCC9.

**Comment by hs0210** [comment]
@Wilco1 Thanks, what I used is GCC8. It can build successfully with GCC10 or newer now.
BTW,  after https://github.com/ARM-software/optimized-routines/commit/cab70b6c8ba3d32421f087cbc18a2220c9fc37a4 commit merge, it fails to compile with GCC8. And the compilation has been successful before.

**Comment by Wilco1** [comment]
GCC 8 is quite old! The error could be a bit clearer, however if you want to build with old compilers, you'll have to disable the vector math functions (set `math-cflags += -DWANT_VMATH=0` in config.mk).

**Comment by hs0210** [comment]
Yes, GCC 8 is old. But for now I have to keep GCC8 on my test env, so I wish I could build it with GCC8.
> however if you want to build with old compilers, you'll have to disable the vector math functions (set math-cflags += -DWANT_VMATH=0 in config.mk

It still failed when I set math-cflags += -DWANT_VMATH=0 in config.mk. Here is the build log, could you please help check, thanks very much.
[build-DWANT_VMATH-0.log](https://github.com/ARM-software/optimized-routines/files/11573433/build-DWANT_VMATH-0.log)

Steps:
```
# gcc -v
gcc version 8.5.0 20210514
# make clean
# echo "math-cflags += -DWANT_VMATH=0" >> config.mk
# make
```

**Comment by hs0210** [comment]
Thanks. Based above comments, the failure is due to a low GCC version. It works with GCC10 or newer version, so close this issue.

**Comment by Wilco1** [comment]
The latest version (https://github.com/ARM-software/optimized-routines/commit/7999fd9f7ed482dc663befc16f56321344c0de1d) will allow you to build again with older compilers. I tried GCC 6.5 and that works perfectly. You no longer need to set WANT_VMATH - it didn't work properly so I removed it. The vector math functions are ignored if the compiler is too old.

**Comment by hs0210** [comment]
That's great! Thanks very much. It works on my env with GCC 8.5 now.
