### ISSUE TITLE
Multi-register loads/stores in __memcmp_aarch64

### ISSUE THREAD

**Issue by ththoma-msft** [ARM-software/optimized-routines#59]
Currently, the NEON loop in `__memcmp_aarch64` uses single-register `ldr` for loads into vector registers, totaling 8 loads over the course of the loop. Naively, it seems like this could be improved significantly using `ldp` or `ld1` for those loads instead (the first being the simpler option in terms of total code changes, due to restrictions imposed by `ld1`'s limited addressing modes), as is done elsewhere in this repo for bulk loads into vector registers, e.g. in `__memchr_aarch64` (ld1) or `__memcpy_aarch64_simd` (ldp).

I suspect that there's some profiling data driving this decision, but in that case it would be interesting to know what it is about `memcmp` specifically that makes this unusual load pattern the most efficient choice, when it isn't in other places.

**Comment by Wilco1** [comment]
If you check the optimization guides you can see that LDP of 128-bit registers has the same throughput as 2 LDR of 128-bit registers. So there is no performance advantage of using LDP here, it's purely which instruction sequence works out best for decode/dispatch.
