### ISSUE TITLE
Magnitude of floating-point constant too large for type 'long double'; maximum is 1.7976931348623157E+308 [-Werror,-Wliteral-range]

### ISSUE THREAD

**Issue by xboxfanj** [ARM-software/optimized-routines#64]
I pulled the latest AOR into Android 14 and got the error below.  Android 14 uses Clang 17.0.2.  Should the constants change, should we disable Wliteral-range, or should I just exempt tgamma128.c from compiling in Android.bp?

external/arm-optimized-routines/math/tgamma128.c:277:32: error: magnitude of floating-point constant too large for type 'long double'; maximum is 1.7976931348623157E+308 [-Werror,-Wliteral-range]
            long double huge = 0x1p+12288L;
                               ^
external/arm-optimized-routines/math/tgamma128.c:280:32: error: magnitude of floating-point constant too small for type 'long double'; minimum is 4.9406564584124654E-324 [-Werror,-Wliteral-range]
            long double tiny = 0x1p-12288L;

**Comment by Wilco1** [comment]
This code requires 128-bit long double, so you have to exclude it in Android. In the future we might move it to a separate directory.

**Comment by xboxfanj** [comment]
Ah right, that makes sense.  I excluded from my downstream project.  Thanks Wilco.  We can close this issue if you'd like.

fyi @enh-google

**Comment by enh-google** [comment]
note that Android _does_ use ld128 for arm64. (for arm32, long double is just double.)

is there going to be a tagged release this year? AOSP is currently on v23.01.

**Comment by Wilco1** [comment]
If that was the AArch64 build then something is wrong if you expected it to use 128-bit long double - the above error message implies long double is 64 bits...

Yes the plan is a release later this month.

**Comment by nsz-arm** [comment]
fixed in https://github.com/ARM-software/optimized-routines/commit/bc2c14ae610a7785a0aeb61789a9613fd482dbab

**Comment by enh-google** [comment]
> If that was the AArch64 build then something is wrong if you expected it to use 128-bit long double - the above error message implies long double is 64 bits...

i've only been taking tagged releases like you advised, so i haven't tried to build _anything_ since this time last year :-)

i was just pointing out to the other guy (who doesn't work on Android/AOSP, but a downstream project) that they probably _do_ want this code, just only in the 64-bit part of their build file.

> Yes the plan is a release later this month.

cool, i'll try to keep an eye out for that so we get it into Android V then (but feel free to ping me directly when it's time!).

**Comment by xboxfanj** [comment]
> 
> i was just pointing out to the other guy (who doesn't work on Android/AOSP, but a downstream project) that they probably _do_ want this code, just only in the 64-bit part of their build file.
> 
Understood, thanks
