### ISSUE TITLE
Difference between math and pl/math

### ISSUE THREAD

**Issue by zoujyjs** [ARM-software/optimized-routines#67]
`exp10` exists both in math and pl/math. `sin(x)` is in math, while `asin(x)` is in pl/math. The doc says that pl/ is separately maintained performance library code.

So should I use math or pl/math for `exp10`? And why no `asin(x)` in math? 

Also the source include `math.h` which introduce name conflicts with libc for most of the routines.

**Comment by Wilco1** [comment]
Scalar `exp10` is only in `math/`. Vector versions of `exp10` are in `pl/`. Most functions are now ported to GLIBC. Some, like `asin`, have a fairly high ULP error, so they are not in GLIBC.

What kind of conflicts do you get? `math_config.h` has various defines that avoid name conflicts when statically linking with GLIBC.

**Comment by Wilco1** [comment]
Most math functions have now been merged in the main math directory.
