### ISSUE TITLE
Meaning of the suffix of routines in the pl/math.

### ISSUE THREAD

**Issue by zoujyjs** [ARM-software/optimized-routines#73]
Is there a specific meaning of suffix `2u` in `acos_2u.c`. And many others like `1u4`, `2u8`.

**Comment by Wilco1** [comment]
It's the ULP error so that you can have multiple implementations of the same math function with different accuracy. The convention is used in other projects such as SLEEF.

**Comment by zoujyjs** [comment]
That make sense! So `atan_2u5.c` interprets to an `atan` routine with aproximatelly 2.5 ulps?  like both asinf (2.41 ulps) and atan (2.27 ulps) has a suffix `2u5`.

**Comment by Wilco1** [comment]
The actual varies a bit with compiler version/options and further optimization, and you don't want to change the filename every few days...
