### ISSUE TITLE
Incorrect licensing

### ISSUE THREAD

**Issue by pgiffuni** [ARM-software/optimized-routines#9]
https://github.com/ARM-software/optimized-routines/blob/6e60567b9bbf59b38c72493faf7cc9eb6ce43c64/math/single/e_rem_pio2.c#L17

Note that all content "nicked from fdlibm" should preserve the originating license.

**Comment by nsz-arm** [comment]
i don't believe such constant values are copyrightable under any legal system, but the entire file got removed so i'm closing this.
